### ISSUE TITLE
Wildcard list index (asterisk)

### ISSUE THREAD

**Issue by PhillippOhlandt** [zackehh/dot-notes-elixir#1]
Hey,

seems like there is no support for the asterisk character as wildcard list index.

Examples:

```elixir
  def test do
    DotNotes.get(%{ "data" => [%{foo: "bar"}, %{foo: "baz"}] }, "data.*.foo")
  end

iex(6)> DotNotesTest.test
** (DotNotes.ParseException) Unable to parse 'data.*.foo' at character '*', column 6!
    (dot_notes) lib/dot_notes/parse_exception.ex:38: DotNotes.ParseException.raise/1
    (dot_notes) lib/dot_notes/keys.ex:30: DotNotes.Keys.execute/3
    (dot_notes) lib/dot_notes/get.ex:20: DotNotes.Get.execute/2
```

```elixir
  def test do
    DotNotes.get(%{ "data" => [%{foo: "bar"}, %{foo: "baz"}] }, "data[*].foo")
  end

iex(7)> DotNotesTest.test
** (DotNotes.ParseException) Unable to parse 'data[*].foo' at character '*', column 6!
    (dot_notes) lib/dot_notes/parse_exception.ex:38: DotNotes.ParseException.raise/1
    (dot_notes) lib/dot_notes/keys.ex:30: DotNotes.Keys.execute/3
    (dot_notes) lib/dot_notes/get.ex:20: DotNotes.Get.execute/2
```

I would have expected:

```elixir
["bar", "baz"]
```

**Comment by whitfin** [comment]
@PhillippOhlandt this library is purely aimed at parsing dot notation; it is not a pattern library - as such `*` won't be supported because it's not valid notation.

**Comment by PhillippOhlandt** [comment]
Do you see a way that I could extend it on my own without having to fork or build my own lib from scratch?
